name: Prettier

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.md"
      - "**.ts"
      - "**.yml"
      - "**.json"
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn install --immutable --immutable-cache --check-cache

      - name: Check
        run: |
          yarn run prettier:check
